### ISSUE TITLE
[Front] サポートメンバーページの実装

### ISSUE THREAD

**Issue by yuta-sksn** [Drop-in-Hachinohe/coderdojo-hachinohe-website#20]
## 概要

サポートメンバーページの実装を行います。

## 利用シナリオ

- サポートメンバーを表示し、サイト訪問者にどのような人たちが CoderDojo に参加しているかを見てもらうためのページです。

## 実装のアイデア

- api からは、チャンピオン、メンター全てが一覧で取得されるので、配列を `reduce`, `map`, `sort` 等を使用して並び替えます（この辺りの実装は実装者の塩梅で）

## その他

- 元のページは現在公開してないため、全体像を見たい場合は @yuta-sksn にメンションしてください。(サービスの仕組み上、全体像のスクリーンショットが撮れませんでした🙏)

**Comment by ITC-kikuuchi** [comment]
@yuta-sksn 
お疲れ様です！
サポートメンバーの説明（`description`）の表示方法に関して質問です！
API から返却された `description` の値は `html` タグを含む文字列となっていますが、
こちらレンダリングして表示する想定をしているということで問題ありませんでしょうか？

また htmlタグを含む文字列をレンダリングする際に、方法として以下の三つがあるのですが、
どれを使うのが望ましいでしょうか？
お手数お掛けいたしますがご確認よろしくお願いいたします！
（もしかしたら他にもやり方はあるかもしれません）
- [dangerouslySetInnerHTML](dangerouslySetInnerHTML)
- [dom-parser-react](https://www.npmjs.com/package/dom-parser-react)
- [html-react-parser](https://www.npmjs.com/package/html-react-parser)

**Comment by yuta-sksn** [comment]
@ITC-kikuuchi 
お疲れ様です！
API から返却されたレンダリング方法に関しては、結論から申し上げますと
サポートメンバーページは [dangerouslySetInnerHTML](https://github.com/Drop-in-Hachinohe/coderdojo-hachinohe-website/issues/dangerouslySetInnerHTML) で問題ありません！👌

理由としましては、

dom-parser-react に関しては、最終更新が一年前であること、npm ページの使用方法を見ると今回の用途では冗長になってしまうことが挙げられます！

もう一つの html-react-parser ですが、こちらは HTML Parser ライブラリを React, Next で使用するならとりあえずこれ！みたいにメジャーなライブラリですね。
こちらは、例えば API から返却された HTML に対して何かしらの検証を行う、加工を行う際に使用するといった使い方になります！もし使用するとしたら開催報告詳細ページですね🙋‍♀️ (例えば、記事内の img タグにポップオーバー機能を差し込みたい時とか)

FYI
https://kray.jp/blog/react-html-parser/

と言った形になります！
よろしくお願いいたします🤲

**Comment by ITC-kikuuchi** [comment]
@yuta-sksn 
返信ありがとうございます！
承知いたしました！
では `dangerouslySetInnerHTML` を用いて実装の方いたします！

**Comment by yuta-sksn** [comment]
@ITC-kikuuchi 
#27 
菊内くん実装分、LGTM で develop に merge しましたので、こちらにも記載いたします！
私の実装分の PR は本日中に発行いたしますね！

**Comment by yuta-sksn** [comment]
こちら無事ステージングで確認できましたので、Close とします！
