### ISSUE TITLE
[Front] 初めて参加される方へページの実装

### ISSUE THREAD

**Issue by yuta-sksn** [Drop-in-Hachinohe/coderdojo-hachinohe-website#6]
## 概要

- 現在稼働している Web サイトのページは[こちら](https://hachinohe.themedia.jp/pages/4569300/page_202101231259)

## 利用シナリオ

- 初めて参加する親子が閲覧するページです。

## 実装のアイデア

- 現状のページを見ると基本的な HTML タグで実装されています。タグの意味や HTML 構造を意識して実装を行います。
- スタイリングは基本的に [Tailwind CSS](https://tailwindcss.com/) を使用してください。
- 幾つかのセクションに分かれているため、それぞれをコンポーネントにしても良いかもしれません。
  - 「CoderDojoはプログラミング教室ではありません」セクション
  - 「CoderDojoにいるいろいろな人たち」セクション
  - 「初めてだから、何をしたら良いかわからない！というお友達へ」セクション
  - 「ご参加希望の方へ」セクション

## その他

- それぞれのセクションを小分けにして PR を発行しても問題ありません！
- 何かあれば (実装上での質問や分からないことなどなど) 、@yuta-sksn にメンションしてください。

**Comment by ITC-kikuuchi** [comment]
@yuta-sksn 
お疲れ様です！
画面の仕様に関しての質問です。
HOME 画面では次回開催以降の要素に、`useFadeInOnScroll`  を用いて、
スクロール時、要素が表示されたときにフェードインされる仕様にしているかと思いますが、
こちらは「初めて参加される方へ」のページでも同様に、各セクションに取り入れた方がよろしいでしょうか？
ご確認よろしくお願いいたします！

**Comment by ITC-kikuuchi** [comment]
@yuta-sksn 
返信ありがとうございます！
承知いたしました！
では、そのように実装の方引き続き進めさせていただきます！

**Comment by yuta-sksn** [comment]
こちら、merge されているので一旦 Close しますね。
